### ISSUE TITLE
Inference and lack of guide issues

### ISSUE THREAD

**Issue by dsilkersahin** [Media-Smart/SKU110K-DenseDet#1]
Hello, I am trying to make an inference of a single image with model checkpoints you shared https://drive.google.com/file/d/1XM8OzRdcbDbSrvlcMgJsFX76lBmdN2Td/view (could you pls specify which model you provided)
But I have encountered some problems which are most probably related mmdet lib version
config .py file (SKU_fusion_bifpn_x101_32x4d.py) and checkpoint_file (DenseDet.pth).

config_file = '/home/./Projects/SKU110K-DenseDet/configs/SKU_fusion_bifpn_x101_32x4d.py'
# download the checkpoint from model zoo and put it in `checkpoints/`
checkpoint_file = '/home/./Projects/SKU110K-DenseDet/DenseDet.pth'

# build the model from a config file and a checkpoint file
model = init_detector(config_file, checkpoint_file, device='cuda:0')

**Error**:
  File "demo/infer_debug.py", line 11, in <module>
    model = init_detector(config_file, checkpoint_file, device='cuda:0')
  File "/home/./Projects/SKU110K-DenseDet/mmdetection/mmdet/apis/inference.py", line 34, in init_detector
    model = build_detector(config.model, test_cfg=config.test_cfg)
  File "/home/./Projects/SKU110K-DenseDet/mmdetection/mmdet/models/builder.py", line 67, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/./Projects/SKU110K-DenseDet/mmdetection/mmdet/models/builder.py", line 32, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/./Projects/SKU110K-DenseDet/sku_venv/lib/python3.7/site-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'num_stages'

**Comment by SteelBeamR** [comment]
I may need to know which of the version your mmdetection is. It seems to be a intrinsic problem in the mmdetection.
My project is based on mmdetection-v1.0rc1, which I didn't emphasize in my guidance. Thanks for your report, and I will edit it later

**Comment by shanudhawale** [comment]
Did you solve this problem even I faced the same? @dsilkersahin @SteelBeamR @mileistone @hxcai @Media-Smart 
Even with the installation of mmdetection -v1.0rc1 this error comes out:
As well there's another issue with python setup.py develop it gives error as 
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
running the high-level API results into this
ImportError: cannot import name 'deform_conv_cuda'

I'm installing my dependencies like this:
!pip install -U torch==1.5.1+cu101 torchvision==0.6.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html
!pip install mmcv-full
!rm -rf mmdetection
!git clone --depth 1 --branch v1.0rc1 https://github.com/open-mmlab/mmdetection.git 

need help!!!!!

**Comment by shanudhawale** [comment]
Solve the Previous Issue by pip install torch==1.4.0 torchvision==0.5.0, this works perfectly!!!
a new issue has arrived at the inference_detector step:
### **_Error:_**
      1 # test a single image and show the results
      2 img = mmcv.imread('images/ss1.jpg')  # or img = mmcv.imread(img), which will only load it once
      3 result = inference_detector(model, img)
      4 # visualize the results in a new window
      5 show_result(img, result, model.CLASSES)

6 frames
/content/gdrive/My Drive/Retail/mmdetection/mmdet/apis/inference.py in inference_detector(model, img)
     84     # forward the model
     85     with torch.no_grad():
---> 86         result = model(return_loss=False, rescale=True, **data)
     87 
     88     return result

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

/content/gdrive/My Drive/Retail/mmdetection/mmdet/core/fp16/decorators.py in new_func(*args, **kwargs)
     47                                 'method of nn.Module')
     48             if not (hasattr(args[0], 'fp16_enabled') and args[0].fp16_enabled):
---> 49                 return old_func(*args, **kwargs)
     50             # get the arg spec of the decorated method
     51             args_info = getfullargspec(old_func)

/content/gdrive/My Drive/Retail/mmdetection/mmdet/models/detectors/base.py in forward(self, img, img_meta, return_loss, **kwargs)
    117             return self.forward_train(img, img_meta, **kwargs)
    118         else:
--> 119             return self.forward_test(img, img_meta, **kwargs)
    120 
    121     def show_result(self, data, result, dataset=None, score_thr=0.3):

/content/gdrive/My Drive/Retail/mmdetection/mmdet/models/detectors/base.py in forward_test(self, imgs, img_metas, **kwargs)
    100 
    101         if num_augs == 1:
--> 102             return self.simple_test(imgs[0], img_metas[0], **kwargs)
    103         else:
    104             return self.aug_test(imgs, img_metas, **kwargs)

/content/gdrive/My Drive/Retail/mmdetection/mmdet/models/detectors/cascade_rcnn.py in simple_test(self, img, img_meta, proposals, rescale)
    340             ms_scores.append(cls_score)
    341 
--> 342             if self.test_cfg.keep_all_stages:
    343                 det_bboxes, det_labels = bbox_head.get_det_bboxes(
    344                     rois,

/usr/local/lib/python3.6/dist-packages/mmcv/utils/config.py in __getattr__(self, name)
     41         elif isinstance(v, int):
     42             parser.add_argument('--' + prefix + k, type=int)
---> 43         elif isinstance(v, float):
     44             parser.add_argument('--' + prefix + k, type=float)
     45         elif isinstance(v, bool):

AttributeError: 'ConfigDict' object has no attribute 'keep_all_stages'
What should be done about this??? @dsilkersahin @SteelBeamR @mileistone @hxcai

**Comment by SteelBeamR** [comment]
Could you tell me the version of package mmcv? Mine is 0.5.9, which is far from the current version.

**Comment by SteelBeamR** [comment]
And I just found that my v1.0rc1 is different from the released version v1.0rc1, especially the cascade part, or you can run the install with the code I supplied.

**Comment by shanudhawale** [comment]
I'm using pip install mmcv==0.4.3 with pip install torch==1.4.0 torchvision==0.5.0
what do you mean by install with the code I supplied, Also as to how to replicate the whole configuration
@SteelBeamR @mileistone @hxcai

**Comment by shanudhawale** [comment]
Could please send the pytorch ,torchvision,cuda, cudnn version with mmcv version,provided git cloning your repo and that could  be used with high level api provided by mmdetection?? @SteelBeamR @mileistone @hxcai @Media-Smart

**Comment by mileistone** [comment]
> Could please send the pytorch ,torchvision,cuda, cudnn version with mmcv version,provided git cloning your repo and that could be used with high level api provided by mmdetection?? @SteelBeamR @mileistone @hxcai @Media-Smart
The main problem should be the mmcv version, you need use the mmcv 0.5.9.

**Comment by mileistone** [comment]
> I'm using pip install mmcv==0.4.3 with pip install torch==1.4.0 torchvision==0.5.0
> what do you mean by install with the code I supplied, Also as to how to replicate the whole configuration
> @SteelBeamR @mileistone @hxcai

install [this](https://github.com/Media-Smart/SKU110K-DenseDet)

**Comment by shanudhawale** [comment]
Thanks, guys totally works for high-level API @SteelBeamR @mileistone

**Comment by jaideep11061982** [comment]
@SteelBeamR is the model trained on sku110k or coco data set ?
Looking at inference_demo.ipynb classes appear to be of coco dataset
