### ISSUE TITLE
bad test result

### ISSUE THREAD

**Issue by mmchen88** [Media-Smart/SKU110K-DenseDet#7]
I test some Shelf images, the detecion result is bad.
Is the model you prove really well trained?
Or some thing wrong with the tool of model upgrading?

I just use tools/upgrade_model_version.py  to upgrade the model weights file, and then edit configs/SKU_fusion_bfp_x101_32x4d.py to the style of V2 by hand. 
my mmdet version is 2.7.0 ,
mmcv version is 1.1.5

**Comment by mmchen88** [comment]
Then i used mmcv v0.5.9 and mmdetection v1.0rc1, the result is much better.

**Comment by Rana-Banerjee** [comment]
@mmchen88 Is it possible for you to share the updated config file please?
